# Generated by Django 5.0.7 on 2024-07-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("letrehozva", models.DateTimeField(auto_now_add=True)),
                ("leado_neve", models.CharField(max_length=50)),
                ("hardware_vagy_szotver_hiba", models.CharField(max_length=50)),
                ("rovid_leiras", models.CharField(max_length=300)),
                ("prioritasa", models.CharField(max_length=30)),
            ],
        ),
    ]
