# Generated by Django 5.0.7 on 2024-07-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_rename_problems_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="aktiv_a_hiba",
            field=models.CharField(default="Igen", max_length=30),
        ),
    ]
